### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by andrzej-jedrzejewski** [andrzej-jedrzejewski/SEBC#2]

**Comment by andrzej-jedrzejewski** [comment]
mysql database has been installed and configured with replica

**Comment by andrzej-jedrzejewski** [comment]
CM 5.8.3 has been installed and following services have been created:
sentry
oozie
hue
hive
zookeper

**Comment by andrzej-jedrzejewski** [comment]
Installation has been verified with host inspector (all green)

**Comment by andrzej-jedrzejewski** [comment]
Done

**Comment by mfernest** [comment]
Please leave your Issues open from now on. @rsiwicki or I will close them once the work has been evaluated.

**Comment by mfernest** [comment]
Please use the `submitted` label to show your lab work is ready for evaluation.
